# Generated by Django 4.0.4 on 2022-06-06 01:33

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=12, verbose_name='名字')),
                ('last_name', models.CharField(max_length=8, verbose_name='姓氏')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生年月日')),
                ('email', models.EmailField(max_length=255, verbose_name='電子信箱')),
                ('phonenumber', models.CharField(max_length=10, verbose_name='聯絡號碼')),
                ('address', models.CharField(max_length=80, verbose_name='地址')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '寵物主人',
                'db_table': '主人資料',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('nickname', models.CharField(blank=True, max_length=10, verbose_name='暱稱')),
                ('category', models.IntegerField(choices=[(1, '狗'), (2, '貓'), (3, '蛇'), (4, '蜘蛛'), (5, '青蛙'), (6, '老鼠'), (7, '鳥類'), (8, '其他')], verbose_name='種類')),
                ('type', models.CharField(max_length=22, verbose_name='品種')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='性別')),
                ('birth_date', models.DateField(verbose_name='出生年月日')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_host', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name_plural': '寵物',
                'db_table': '寵物資料',
            },
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField(choices=[(1, '閒聊'), (2, '寵物飲食'), (3, '寵物生病'), (4, '其他')], verbose_name='主題')),
                ('title', models.CharField(max_length=50, verbose_name='標題')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='petManage.pets', verbose_name='該紀錄的寵物')),
            ],
            options={
                'verbose_name_plural': '留言板',
                'db_table': '留言板',
            },
        ),
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, verbose_name='名字')),
                ('last_name', models.CharField(max_length=8, verbose_name='姓氏')),
                ('birth_date', models.DateField(verbose_name='出生年月日')),
                ('email', models.EmailField(max_length=255, verbose_name='電子信箱')),
                ('phonenumber', models.CharField(max_length=10, verbose_name='聯絡號碼')),
                ('start_time', models.DateField(verbose_name='開始日期')),
                ('end_time', models.DateField(verbose_name='結束日期')),
                ('address', models.CharField(max_length=80, verbose_name='地址')),
                ('pet', models.ManyToManyField(to='petManage.pets')),
            ],
            options={
                'verbose_name_plural': '協助飼養寵物者',
                'db_table': '協助飼養寵物者',
            },
        ),
        migrations.CreateModel(
            name='PetRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='填表日期')),
                ('number_of_excretion', models.IntegerField(blank=True, null=True, verbose_name='當日排泄次數')),
                ('number_of_meals', models.IntegerField(blank=True, null=True, verbose_name='當日用餐次數')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='寵物體重')),
                ('status', models.IntegerField(choices=[(1, '健康'), (2, '不舒服')], verbose_name='身體狀況')),
                ('photos', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='日常照')),
                ('hospital_name', models.CharField(blank=True, max_length=22, verbose_name='醫院/診所的名稱')),
                ('diseases', models.CharField(blank=True, max_length=255, verbose_name='症狀或病名')),
                ('heal_status', models.IntegerField(blank=True, choices=[(1, '症狀改善'), (2, '症狀無改變'), (3, '症狀加劇')], null=True, verbose_name='治療後狀況')),
                ('notes', models.TextField(blank=True, verbose_name='備註:')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petManage.pets', verbose_name='該紀錄寵物')),
            ],
            options={
                'verbose_name_plural': '寵物紀錄',
                'db_table': '寵物紀錄',
                'unique_together': {('date', 'pet')},
            },
        ),
    ]
