# Generated by Django 4.0.4 on 2022-06-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petrecords',
            options={'verbose_name_plural': '寵物紀錄'},
        ),
        migrations.AlterModelTable(
            name='petrecords',
            table='寵物紀錄',
        ),
    ]
