# Generated by Django 4.0.4 on 2022-06-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petManage', '0002_remove_hosts_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name ='hosts',
            name ='birth_date',
            field = models.DateField(blank=True, null=True, verbose_name='出生年月日'),
        ),
    ]
