# Generated by Django 4.0.4 on 2022-06-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petManage', '0002_alter_petrecords_options_alter_petrecords_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistants',
            name='phonenumber',
            field=models.CharField(max_length=10, verbose_name='電話號碼'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='phonenumber',
            field=models.CharField(max_length=10, verbose_name='手機號碼'),
        ),
    ]
