# Generated by Django 4.0.4 on 2022-06-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petManage', '0003_hosts_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='category',
            field=models.IntegerField(choices=[(1, '狗'), (2, '貓'), (3, '蛇'), (4, '蜘蛛'), (5, '青蛙'), (6, '老鼠'), (7, '鳥類'), (8, '其他')], verbose_name='種類'),
        ),
    ]
