# Generated by Django 4.0.4 on 2022-06-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petManage', '0004_alter_assistants_phonenumber_alter_hosts_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_host', to='petManage.hosts', verbose_name='主人'),
        ),
    ]
